import type { Metadata } from "next";
import Link from "next/link";
import { categories } from "@/data/categories";
export const metadata:Metadata={title:"사이트 소개와 편집 기준",description:"한국에서 살아남기의 주제, 자료 확인 기준과 정정 문의 경로를 안내합니다.",alternates:{canonical:"/about"}};
export default function AboutPage(){return <div className="max-w-3xl mx-auto px-4 sm:px-6 py-14"><p className="text-sm font-bold text-red-700 mb-3">이 사이트를 읽는 방법</p><h1 className="text-3xl font-black mb-5">한국에서 살아남기 소개</h1><p className="text-lg text-slate-600 leading-relaxed mb-10">중장년과 가족이 연금·지원·건강·디지털 생활·재취업에 필요한 조건을 확인하고 다음 행동을 준비할 수 있도록 정보를 정리합니다.</p><div className="space-y-9 text-slate-700 leading-relaxed">
<section><h2 className="text-xl font-bold text-slate-900 mb-3">무엇을 다루나요</h2><div className="grid sm:grid-cols-2 gap-3">{categories.map(c=><Link key={c.id} href={`/category/${c.slug}`} className="rounded-xl border border-slate-200 p-4 hover:bg-slate-50"><span className="font-bold block mb-1">{c.icon} {c.label}</span><span className="text-sm">{c.description}</span></Link>)}</div></section>
<section><h2 className="text-xl font-bold text-slate-900 mb-3">자료를 확인하는 기준</h2><ul className="list-disc pl-5 space-y-3"><li>제도의 대상·금액·일정은 해당 연도 공식 자료를 우선 확인하고 글 끝에 확인 경로를 연결합니다.</li><li>국가 공통 기준과 지역·기관·개인 조건을 구분합니다. 블로그의 설명만으로 수급 가능 여부나 지급액을 확정하지 않습니다.</li><li>건강 글은 기록과 진료 준비를 돕습니다. 개인별 진단·약 복용·운동 처방을 대신하지 않습니다.</li><li>금융·세금 글은 비교할 질문을 정리합니다. 특정 상품 가입이나 계약을 권유하지 않습니다.</li></ul></section>
<section><h2 className="text-xl font-bold text-slate-900 mb-3">글의 작성과 상황 예시</h2><p>글은 사이트명 ‘한국에서 살아남기’로 제공합니다. 본문에 등장하는 준비·막힘 사례는 설명을 위한 가정이며 실제 가족 경험담, 상담 실적이나 이용자 후기처럼 제시하지 않습니다. 사진은 주제를 이해하는 데 쓰는 자료 이미지이며 해당 기관 방문이나 개인의 경험을 증명하지 않습니다.</p></section>
<section><h2 className="text-xl font-bold text-slate-900 mb-3">날짜와 정정</h2><p>글의 업데이트 날짜는 본문을 수정한 날짜입니다. 연결한 기관의 안내도 이후 바뀔 수 있으므로 신청 직전에는 해당 기관의 현재 공고를 확인하세요. 오류를 발견했다면 글 주소, 문제가 되는 문장과 공식 확인 자료를 문의로 알려 주세요. 주민등록번호, 계좌번호와 상세 의료 기록은 보내지 마세요.</p></section>
<section><h2 className="text-xl font-bold text-slate-900 mb-3">운영과 문의</h2><p>이 사이트는 정부기관이나 신청 대행 서비스가 아닙니다. 개인별 심사와 계약·진료 판단은 담당 창구에서 확인해야 합니다. 광고가 표시될 수 있으며 정보 확인 링크와 광고를 구분해서 이용해 주세요.</p><div className="flex flex-wrap gap-4 mt-4 font-semibold text-red-700"><Link href="/contact">정정·주제 문의 →</Link><Link href="/privacy-policy">개인정보처리방침 →</Link><Link href="/disclaimer">면책 안내 →</Link></div></section>
</div></div>;}
